owner: toitu
repo: upptime

sites:
  - name: Toitu
    url: https://toitu.co.nz
  - name: Client Portal
    url: https://prod-client-portal.prod.toitu.co.nz
  - name: Emanage
    url: https://emanage.toitu.co.nz
  - name: Assurance App
    url: https://prod-assurance.prod.toitu.co.nz
  - name: Assurance Admin
    url: https://prod-account-manager-portal.prod.toitu.co.nz/

status-website:
  baseUrl: /upptime
  logoUrl: "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIGZpbGw9Im5vbmUiIHZpZXdCb3g9IjAgMCA0OCA0OCIgaGVpZ2h0PSI0OCIgd2lkdGg9IjQ4Ij4NCjxwYXRoIGZpbGw9IiMyMDFFMUYiIGQ9Ik0yMS4yMjU0IDAuMDA3MTI0OTZDMTAuNTU4MyAwLjM0NTE2NiAtMC40MDk2MDIgMTAuNTcwOSAwLjAxMTc2NzIgMjQuMDcxOUMwLjA3MzEzMTYgMjYuMDA5NSAwLjMzMjkwNyAyNy42NjQ2IDAuNjExMDkyIDI5LjA5NTFDMy4wNDkzIDI3LjkwNzkgMy43NDQ3NyAyNS44MjQgMy43NjUyMiAyMy42NzgyQzMuODc3NzMgMTEuNzIxMSAxMy4zMTE1IDQuMTI5NTggMjAuODY5NSAzLjg5MDQ3QzI0LjkwMTIgMy43NjI2OCAyNy4wMTAxIDUuNzAyMjkgMjcuMDc5NiA3LjkyNDI5QzI3LjA4OTggOC4yNjQzOSAyNy4wMDE5IDguNzM2NDEgMjYuODY2OSA5LjA1Nzk3QzI4LjY1ODcgOS4wMDIzMSAzMC4xMTEgNy43Njc2NCAzMC4wNDc2IDUuNzMxMTVDMjkuOTUzNSAyLjcwMzIxIDI2LjU1NiAtMC4xNjE4OTYgMjEuMjI1NCAwLjAwNzEyNDk2Wk00LjkwNzA4IDM4LjAwMzFDMTAuNTMyMSA0Ny4xNDI2IDI0LjgwMzUgNTEuNjAxIDM2LjE5NDcgNDQuNDgzNkMzNy44MjkxIDQzLjQ2MTIgMzkuMTIxOCA0Mi40MDc5IDQwLjIxMjEgNDEuNDQ5NUMzNy45NzQzIDM5LjkxMzkgMzUuODM0NyA0MC4zNTA4IDMzLjk4MTUgNDEuNDA2MkMyMy42NDc4IDQ3LjI4NDggMTIuNDA3OCA0Mi44NDkgOC40MjMyNSAzNi4zNzA2QzYuMjk4IDMyLjkxODEgNi45MDk2IDMwLjEwNjYgOC43ODMyNiAyOC45MzU4QzkuMDcxNjcgMjguNzU2NSA5LjUyMTY4IDI4LjU5NTcgOS44NjUzMiAyOC41NTQ1QzguOTIwMzEgMjcuMDE4OCA3LjEzMjU2IDI2LjM2OTYgNS40MTQzNSAyNy40NDM1QzIuODYxNTkgMjkuMDM4OCAyLjA5NjU5IDMzLjQzNTQgNC45MDcwOCAzOC4wMDMxWk0zNS42NDM4IDIuNjk5NDdDNDcuNDU4NSA5LjA4MzA4IDUwLjc2MiAyMy43NjcyIDQ1LjcxOTkgMzMuMjQ0OEM0My4xOTk4IDM3Ljk4MTUgMzkuMDM5MyAzOS41MTI5IDM2LjM5MDQgMzguMDgyNUMzNC42MDg4IDM3LjExOTkgMzQuMjczNCAzNS4yMzM4IDM1LjEyMDIgMzMuNjQyNkMzNS4zMjg4IDMzLjkyMDggMzUuNjkwOSAzNC4yMzQxIDM1Ljk4OTUgMzQuMzk0OUMzNy45MzI3IDM1LjQ0NjIgNDAuNjU1MiAzNC41NzQyIDQyLjU1OTYgMzAuOTkzOUM0Ni4xMzMgMjQuMjc2NCA0NC4zMjQ4IDEyLjI0OTEgMzQuMTA1NiA2LjE3MDU3QzMyLjI3NDkgNS4wODAxOCAzMC44Mjg4IDMuNDMzMjYgMzEuMDI5MiAwLjcxMDM4NEMzMi4zOTc2IDEuMTgyNCAzMy45NTAyIDEuNzg0MjggMzUuNjQzOCAyLjY5OTQ3WiIgY2xpcC1ydWxlPSJldmVub2RkIiBmaWxsLXJ1bGU9ImV2ZW5vZGQiLz4NCjwvc3ZnPg=="
  name: "Toitū Uptime"
